// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlmh8MlcAifc4wjRyV3AXBmkpB0jwevLg',
    appId: '1:121049807355:web:8046571b147e8c34f1f35e',
    messagingSenderId: '121049807355',
    projectId: 'barber-cda96',
    authDomain: 'barber-cda96.firebaseapp.com',
    storageBucket: 'barber-cda96.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8on7Dp3GSSHyM0wrlqP8Ujkaupj7sqI4',
    appId: '1:121049807355:android:52c08228a891ba05f1f35e',
    messagingSenderId: '121049807355',
    projectId: 'barber-cda96',
    storageBucket: 'barber-cda96.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpFHdhjfdD5LLH3yXL3ynPmRiBSVKotmg',
    appId: '1:121049807355:ios:fd7a84e0b7c30a74f1f35e',
    messagingSenderId: '121049807355',
    projectId: 'barber-cda96',
    storageBucket: 'barber-cda96.appspot.com',
    iosBundleId: 'com.example.barberApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpFHdhjfdD5LLH3yXL3ynPmRiBSVKotmg',
    appId: '1:121049807355:ios:fd7a84e0b7c30a74f1f35e',
    messagingSenderId: '121049807355',
    projectId: 'barber-cda96',
    storageBucket: 'barber-cda96.appspot.com',
    iosBundleId: 'com.example.barberApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlmh8MlcAifc4wjRyV3AXBmkpB0jwevLg',
    appId: '1:121049807355:web:e470059dec403850f1f35e',
    messagingSenderId: '121049807355',
    projectId: 'barber-cda96',
    authDomain: 'barber-cda96.firebaseapp.com',
    storageBucket: 'barber-cda96.appspot.com',
  );
}
